
2020-12-27 00:08:28,032 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:539]
2020-12-27 00:27:48,812 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:539]
2020-12-27 00:27:54,359 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:27:56,528 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:28:37,106 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:28:37,922 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:28:43,436 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:28:46,100 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:28:49,237 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    "num_up_coming_show":Numshow
NameError: name 'Numshow' is not defined
2020-12-27 00:31:07,518 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    })
NameError: name 'Numshow' is not defined
2020-12-27 00:31:09,043 ERROR: Exception on /venues [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 71, in venues
    })
NameError: name 'Numshow' is not defined
2020-12-27 00:32:16,186 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 00:36:42,212 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 01:03:39,231 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 01:13:40,778 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 01:13:42,980 ERROR: Exception on /shows [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 458, in shows
    Shows = Show.query.get().all()
TypeError: get() missing 1 required positional argument: 'ident'
2020-12-27 01:13:46,686 ERROR: Exception on /shows [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 458, in shows
    Shows = Show.query.get().all()
TypeError: get() missing 1 required positional argument: 'ident'
2020-12-27 01:13:48,816 ERROR: Exception on /shows [GET] [in /Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aisha/FSND/projects/01_fyyur/starter_code/app.py", line 458, in shows
    Shows = Show.query.get().all()
TypeError: get() missing 1 required positional argument: 'ident'
2020-12-27 01:16:03,314 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 23:29:19,422 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 23:45:30,328 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 23:47:56,549 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 23:57:45,318 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-27 23:57:46,003 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:09:27,279 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:09:39,234 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:03,500 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:11,297 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:17,614 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:34,199 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:36,495 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:42,586 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:10:43,189 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:12:22,131 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 00:23:45,249 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 08:42:36,251 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 08:51:06,960 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 08:52:45,130 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 08:53:18,201 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 08:59:11,811 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 09:01:52,014 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 09:06:56,349 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 09:21:21,909 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 09:25:30,969 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:534]
2020-12-28 09:27:17,407 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:534]
2020-12-28 09:29:33,610 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:534]
2020-12-28 09:31:36,737 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:531]
2020-12-28 09:43:16,437 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:520]
2020-12-28 09:46:17,501 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:511]
2020-12-28 10:14:12,988 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:553]
2020-12-28 10:15:18,064 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:553]
2020-12-28 10:19:37,531 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:20:12,804 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:21:10,303 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:21:17,267 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:21:41,151 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:22:22,953 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:23:09,299 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:24:09,830 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:24:17,055 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:24:27,999 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:24:31,577 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:24:32,242 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:27:47,781 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:536]
2020-12-28 10:30:34,262 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:508]
2020-12-28 10:34:15,145 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:545]
2020-12-28 10:35:25,523 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:36:27,873 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 10:43:41,588 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:04:46,326 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:07:16,725 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:07:27,832 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:18:16,462 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:18:44,826 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:18:47,791 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:25:35,249 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:26:34,680 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:27:52,330 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:41:01,847 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:41:24,578 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:41:27,660 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:41:30,744 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 11:44:15,579 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:545]
2020-12-28 11:53:25,690 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 11:57:43,094 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 11:59:39,100 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 11:59:58,446 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 12:01:45,119 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 12:02:05,472 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 12:04:09,769 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 12:22:28,483 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 12:22:44,593 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 19:17:45,654 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:551]
2020-12-28 19:29:24,273 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:554]
2020-12-28 19:37:30,623 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 19:40:16,037 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 19:44:39,014 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 19:49:13,149 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 19:49:31,410 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:18:21,202 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:18:21,965 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:18:46,188 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:18:54,275 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:556]
2020-12-28 20:22:19,656 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:556]
2020-12-28 20:31:24,727 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:556]
2020-12-28 20:32:10,630 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:556]
2020-12-28 20:34:16,360 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:547]
2020-12-28 20:37:57,275 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:38:56,955 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:39:09,471 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:41:00,545 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:557]
2020-12-28 20:42:09,413 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:42:26,179 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:547]
2020-12-28 20:42:55,950 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:44:19,306 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:44:45,329 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:45:18,767 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:46:11,221 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:46:54,417 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:546]
2020-12-28 20:48:41,503 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:548]
2020-12-28 20:49:12,383 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:548]
2020-12-28 20:52:57,934 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:548]
2020-12-28 20:57:33,100 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:548]
2020-12-28 20:59:38,772 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:548]
2020-12-28 21:02:05,265 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:535]
2020-12-28 21:04:36,007 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:535]
2020-12-28 21:05:16,329 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:535]
2020-12-28 21:18:22,874 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:527]
2020-12-28 21:19:12,842 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:527]
2020-12-28 21:55:30,873 INFO: errors [in /Users/aisha/FSND/projects/01_fyyur/starter_code/app.py:527]
